### ISSUE TITLE
only works properly in terminal session

### ISSUE THREAD

**Issue by kitingChris** [vintitres/gnome-shell-google-calendar#25]
On Ubuntu 12.04 the script does only work when started in a terminal without forking to the background.
When added as autostart nothing happens :(

**Comment by bertrand47** [comment]
I have the same problem. Is there a way to launch at startup ?

**Comment by jdhoek** [comment]
I have the same problem under Ubuntu 12.04. Is there a way to find out what is going wrong? I have tried redirecting the script's output to a file, but it doesn't seem to work then either.

**Comment by bertrand47** [comment]
an answer from ubuntu forum that seem to work for me.
Just add this command to applications at startup:
sh -c "python ~/gnome-shell-google-calendar/gnome-shell-google-calendar.py"

**Comment by kitingChris** [comment]
unfortunatelly this does not work either. I guess it has something to do with the choosing of the account. At me I get asked everytime I call the python script in the terminal.

**Comment by jdhoek** [comment]
Interesting. :)

By combining the posts of @bertrand47 and @chris1412 we get a working solution. Apparently, @vintitres helpfully included a command line flag to choose which account to use, so use this as the start-up command:

`sh -c "python PATH_TO_SCRIPT --account=ACCOUNT_EMAIL"`

That makes the script choose the account you want instead of asking for it.

**Comment by kitingChris** [comment]
thanks that works!. Would be good to mention that in the wiki!

**Comment by piotrplenik** [comment]
https://github.com/vintitres/gnome-shell-google-calendar/wiki/Run-gnome-shell-google-calendar-on-startup

**Comment by kitingChris** [comment]
thx a lot!
