### ISSUE TITLE
Error on Fedora 16

### ISSUE THREAD

**Issue by mamchenkov** [vintitres/gnome-shell-google-calendar#5]
I've installed all requirements via RPMs on Fedora 16.  When I try to run the script, it asks me for email address and password, shows me the list of my calendars, then hangs for a bit, and then throws this error message:
# 

Checking if actual month events need update...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "./gnome-shell-google-calendar.py", line 147, in scheduler
    if self.months[get_month_key(datetime.now())].\
# KeyError: (1319922000, 1322949599)

If I run it again, it logs in correctly, gets the list of calendars, and then after a while throws the same error.

**Comment by mamchenkov** [comment]
Sorry, forgot about the formatting ... here is once again now

```

Checking if actual month events need update...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./gnome-shell-google-calendar.py", line 147, in scheduler
    if self.months[get_month_key(datetime.now())].\
KeyError: (1319922000, 1322949599)
```

**Comment by vintitres** [comment]
Do you use gnome3? Try running dbus-monitor and clicking on date to show calendar, does it output anythig then?

**Comment by mamchenkov** [comment]
Yes, I was using Gnome3 when I saw the error.  In fact it was Gnome 3.2 from the Fedora 16 distribution.

I have temporarily removed it and switched to KDE, so I can't run the dbus-monitor test.  I will do so later when I re-install it.

**Comment by linsomniac** [comment]
This looks like it's a bug in the gnome-shell-google-calendar code, the current month somehow isn't in the "self.months" dictionary.  When you say that it "hangs for a bit", by "a bit" do you mean "around 60 seconds"?  I wonder because the code in scheduler() does a "sleep(60)" then checks to see if the month needs an update.

I'm wondering if there's an issue that is causing your calendars to not load in 60 seconds.

I believe I've fixed this problem in my fork, so at least the above traceback doesn't happen.  However, I wonder if there is some sort of problem with your login or network that was leading to not getting calendar information within 60 seconds.  Please try my fork and report back on what you see.
